apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: mujtaba-mlops
  labels:
    app: frontend
    owner: mujtaba-junaid-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        owner: mujtaba-junaid-ops
    spec:
      containers:
      - name: react
        image: mujtaba-stock-classifier-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
          name: http
        env:
        - name: VITE_API_URL
          value: "http://fastapi-service.mujtaba-mlops:8000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mujtaba-mlops
  labels:
    app: frontend
    owner: mujtaba-junaid-ops
spec:
  type: LoadBalancer
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: frontend
